#!/bin/bash
# Universal Nova Interface - Simple Syntax, Omni-Language Execution
SCRIPT_PARAM="$1"

if [ -z "$SCRIPT_PARAM" ]; then
    echo "Usage: nova \"Nova.command()\""
    exit 1
fi

./Nova_Omni_Core/nova_binary "$SCRIPT_PARAM"
